import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "ULSVDL Formações",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // Caminho relativo à pasta /public
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="pt">
        <body className={dmSans.className}>
          <Providers>
            <div className="root-layout">{children}</div>
          </Providers>
          <Toaster richColors closeButton />
        </body>
      </html>
    </ClerkProvider>
  );
}
